version: "3.7"

volumes:
  logs:
    driver: local

services:
  consumer:
    image: thebiggive/php:dev-8.1
    command: composer run messenger:consume
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - matchbot_matchbot
# Redis is defined in MatchBot. Uncomment this and `redis` service if you need to run ClaimBot standalone.
#    depends_on:
#      - redis

#  redis:
#    image: redis:7.1
#    networks:
#      - matchbot

networks:
  matchbot_matchbot:
    external: true
